# Generated by Django 5.1 on 2024-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_divider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='media')),
                ('point1', models.TextField(verbose_name='First Point Text')),
                ('icon1', models.CharField(max_length=255, verbose_name='Icon Class Name')),
            ],
        ),
    ]
