# Generated by Django 5.1 on 2024-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon1',
            field=models.CharField(max_length=255, verbose_name='First Icon Class Name'),
        ),
    ]
