# Generated by Django 5.1 on 2024-08-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feature_icon1'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon2',
            field=models.CharField(default='default_icon_class', max_length=255, verbose_name='Second Icon Class Name'),
        ),
        migrations.AddField(
            model_name='feature',
            name='point2',
            field=models.TextField(default='default_point_text', verbose_name='Second Point Text'),
        ),
    ]
