# Generated by Django 5.1 on 2024-08-10 09:27

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('address_icon', models.CharField(max_length=255)),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone_icon', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('email_icon', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ContactUs',
            },
        ),
    ]
