# Generated by Django 5.1 on 2024-08-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_feature1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('space', models.CharField(max_length=255)),
                ('bandwidth', models.CharField(max_length=255)),
                ('themes', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='feature1',
            options={'verbose_name_plural': 'Features1'},
        ),
    ]
