# Generated by Django 5.1 on 2024-08-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('icon1', models.CharField(max_length=255)),
                ('point1', models.CharField(max_length=255)),
                ('icon2', models.CharField(max_length=255)),
                ('point2', models.CharField(max_length=255)),
                ('icon3', models.CharField(max_length=255)),
                ('point3', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('massage', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
            ],
        ),
    ]
